---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{.Service}}-feature-{{.Release}}
spec:
  rules:
    - host: {{.Service}}-feature-{{.Release}}.local
      http:
        paths:
        - path: /
          backend:
            serviceName: {{.Service}}-feature-{{.Release}}
            servicePort: 8080