apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{.Service}}-feature-{{.Release}}-db-credentials
  namespace: apps
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{.Environment}}-vault
    kind: ClusterSecretStore
  target:
    name: {{.Service}}-feature-{{.Release}}-db-credentials
    template:
      engineVersion: v2
      data:
        SPRING_DATASOURCE_USERNAME: "{{"{{"}} .username {{"}}"}}"
        SPRING_DATASOURCE_PASSWORD: "{{"{{"}} .password {{"}}"}}"
  data:
    - secretKey: username
      remoteRef:
        key: secret/cluster-{{.Environment}}/postgres/credentials/{{.Service}}-feature-{{.Release}}
        property: username
    - secretKey: password
      remoteRef:
        key: secret/cluster-{{.Environment}}/postgres/credentials/{{.Service}}-feature-{{.Release}}
        property: password