---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.service}}-feature-{{.release}}
  name: {{.service}}-feature-{{.release}}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{.service}}-feature-{{.release}}