apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: {{.service}}-feature-{{.release}}
spec:
  serviceAccountName: fluxcd
  interval: 1m
  path: "./apps/{{.service}}-feature-{{.release}}"
  sourceRef:
    kind: GitRepository
    name: apps
    namespace: apps-fluxcd
  prune: true